export const GET_GLOBAL_INFO = "GET_GLOBAL_INFO";
export const GET_COUNTRIES_INFO = "GET_COUNTRIES_INFO";
export const HANDLE_FAVOURITE = "HANDLE_FAVOURITE";
export const REFRESH_FAVORITES = "REFRESH_FAVORITES";
